server:
  port: 1702

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/attendance
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
    allow-circular-references: true
cgs:
  default:
    leave_type_id: 18
  thread:
    pool:
      name: cgs_scheduler_attendance_
      size: 10
  attendance:
    interval-in-cron: 0 0 7 * * *
#    For example, a cron expression: 0 15 10 * * * is triggered to run at 10:15 a.m. every day ( every 0th second, 15th minute, 10th hour, every day)
# cgs.default.leave_type_id