server:
  port: 8092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: CGS_SCHEDULER
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/attendance
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
    allow-circular-references: true
#    web-application-type: reactive
cgs:
  default:
    leave_type_id: 18
    public_leave_id: 19
  thread:
    pool:
      name: cgs_scheduler_attendance_
      size: 10
  scheduler:
    attendance:
      interval-in-cron: 0 58 13 * * *
    leave:
      interval-in-cron: 0 56 14 * * *
#    For example, a cron expression: 0 15 10 * * * is triggered to run at 10:15 a.m. every day ( every 0th second, 15th minute, 10th hour, every day)
# cgs.default.leave_type_id
